name: Deploy to DCL TEST

on:
  push:
    branches:
      - testing

env:
  DCL_PRIVATE_KEY: ${{ secrets.DCL_PRIVATE_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy scene
      run: npx @dcl/sdk-commands deploy -t linker-server.decentraland.today --skip-validations true -b --skip-build
